# Generated by Django 5.0.2 on 2024-03-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField()),
                ('date', models.DateField()),
                ('customer', models.CharField(max_length=100)),
                ('revenue_source', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('haircut_percent', models.IntegerField()),
                ('daily_fee_percent', models.DecimalField(decimal_places=3, max_digits=7)),
                ('currency', models.CharField(max_length=3)),
                ('expected_payment_duration', models.IntegerField()),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['revenue_source'], name='invoice_pro_revenue_74b57a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('invoice_number', 'customer'), name='unique_invoice_number_customer'),
        ),
    ]
